name: Release CLI
on:
  workflow_dispatch:
  # push:
  #   branches: [main]

concurrency:
  group: "release-cli"

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 24
    - run: npm ci
    - run: npm run build:cli
    - run: cd packages/cli && npx semantic-release-monorepo
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        # Need owner/admin account to bypass branch protection
        GIT_COMMITTER_NAME: sinedied
        GIT_COMMITTER_EMAIL: noda@free.fr
